### PR TITLE
Add styles and markup for blank SRP

### LINKED ISSUE #29: I know when there are no results for my filter combination
So that I know that the empty page is because nothing matched my filter request, rather than thinking it's a bug, I should see a message telling me that

Acceptance Criteria
Given that I'm an 18F employee
And there are no team members who have CHI as their location, and have listed Javascript as a skill
When I filter for team members in the Chicago Office (CHI) who are skilled in Javascript
I should see a message telling me that there are no matches to my request

### PR DESCRIPTION
**Pull request by andrewmaier**
Closes #29 
cc: @mtorres253 @jbarnicle 

I tried to add a helpful message here, FYI, with the ability to clear filters.
`<p>No team members match your filters. Perhaps <a href="/">clear your filters</a> and start over?</p>`

### CODE REVIEW

**Comment by mtorres253** [comment]
Whoops, @andrewmaier tests aren't passing. Can you take a look?

**Comment by jbarnicle** [comment]
@andrewmaier - it looks like travis is taking issue with this  `<a href="/">`

**Comment by andrewmaier** [comment]
@mtorres253 @jbarnicle Which test failed? It's also worth noting that I'm just submitting this request as a potential solution, not a production-ready one. I didn't write the test... :(

**Comment by jbarnicle** [comment]
@andrewmaier remove the anchor tag around clear your filters and the test should pass.   `Perhaps <a href="/">clear your filters</a> and start over?`

**Pull request merged**
